name: Test

on: [push]

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  stateful:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [1]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.8.0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Install window server
        run: sudo apt-get install -y fluxbox

      - name: Run tests
        run: |
          Xvfb :20 -screen 0 1920x1080x16 &
          sleep 1 &&
          DISPLAY=:20 fluxbox -log /tmp/fluxbox.log &
          'parallel --lb --halt now,success=1,fail=1 ::: \
          "pnpm dev" \
          "pnpm wait-on http://localhost:3000 && DISPLAY=:20 pnpm synpress:ci:stateful --parallel --ci-build-id ${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}"'
        env:
          NEXT_PUBLIC_GRAPH_URI: https://api.thegraph.com/subgraphs/name/tateb/enssubdomaincount

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: synpress-screenshots
          path: e2e/screenshots

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: synpress-videos
          path: e2e/videos
